import type { Metadata } from 'next';
import { Manrope } from "next/font/google";
import './globals.css';
import { Header } from '@/components/Header';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
