quarkus:
  http:
    port: 8080
  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rest:
    path: /api/v1
  smallrye-openapi:
    info-title: Atlas
    info-version: 1.0.0
  datasource:
    db-kind: postgresql
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:5432/atlas